version: "3.1"

services:
  drupal:
    image: drupal:latest
    ports:
      - 8081:80
    environment:
      DRUPAL_DB_HOST: db
      DRUPAL_DB_NAME: drupal
      DRUPAL_DB_USER: drupal
      DRUPAL_DB_PASSWORD: drupal
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: root_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8082:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password

  composer:
    image: composer:2.1.9 # Composer PHP 8.1 -versiolla
    volumes:
      - .:/app
    working_dir: /app
    environment:
      PHP_EXTENSION_GD: "true"
